### ISSUE TITLE
Rewarding everything after Ragnaros.

### ISSUE THREAD

**Issue by karyzan** [evil-morfar/RCLootCouncil_Classic#9] opened 2020-01-19 20:16 UTC
Hey. When rewarding everything on Ragnaros, I only get a couple of items from ragnaros himself in the reward system even tho we used reward later on everything. 
Thank you.

**Comment by evil-morfar** [comment] 2020-01-19 20:54
Just to confirm; you started the session with `/rc award` while the Session Frame was already populated with items from Ragnaros?
If that's indeed the case, then I'd need to have a look at your saved variables file to investigate it.

**Comment by karyzan** [comment] 2020-01-19 21:29
No. I checked the award later box and I looted all the Ragnaros items. And after that, I did /rc award but only two items showed up, and I had like 20+ items in my inventory.

So all the other previous bosses wasn't shown up as reward.

**Comment by webbelito** [comment] 2020-01-19 23:23
I can confirm that when I used `/rc award` after we killed Ragnaros and had all items in my bag including the loot from Ragnaros,

The message I got back was that I had no loot available to distribute however I had +30 items in my inventor that I had to distribute manually so something is broke, might be the SavedVariable files.

**Comment by karyzan** [comment] 2020-01-19 23:26
[RCLootCouncil_Classic.zip](https://github.com/evil-morfar/RCLootCouncil_Classic/files/4083904/RCLootCouncil_Classic.zip)

**Comment by evil-morfar** [comment] 2020-01-20 00:39
Your log shows me the addon failed to detect the items in your bags, meaning they weren't registered properly. They were later removed automatically as it thought they were no longer tradeable - which you should have seen a message informing you about.

Question is, have you experienced an unusual amount of latency? I can adjust the timings of the detection quite easily, I just wonder if this is a sudden issue, as it has worked perfectly fine in the past.

**Comment by karyzan** [comment] 2020-01-20 00:49
> Your log shows me the addon failed to detect the items in your bags, meaning they weren't registered properly. They were later removed automatically as it thought they were no longer tradeable - which you should have seen a message informing you about.
> 
> Question is, have you experienced an unusual amount of latency? I can adjust the timings of the detection quite easily, I just wonder if this is a sudden issue, as it has worked perfectly fine in the past.

Webbelito was the masterlooter last raid and had the same issue so he gave it to me this week and I had the same problem. I got a disconnect during the raid tonight. I have no latency otherwise. So no I've never gotten it to work in raid. 

We tried it in RFC some days prior to raid and it was working fine.

I'm using elvui could it be the bag addon in that interfering?
Thanks in advance!

**Comment by evil-morfar** [comment] 2020-01-20 00:58
Alright.

> I'm using elvui could it be the bag addon in that interfering?

Not likely. There's upwards of 2 seconds delay between sending the "loot" command until the item disappears from the loot list - which is 10 times longer than normal.

**Comment by karyzan** [comment] 2020-01-20 01:09
> Alright.
> 
> > I'm using elvui could it be the bag addon in that interfering?
> 
> Not likely. There's upwards of 2 seconds delay between sending the "loot" command until the item disappears from the loot list - which is 10 times longer than normal.

The variable file was shared from webbe to me so I could get the history of loot. Could it help to remove that then? Or do you think you know what the issue is?

**Comment by evil-morfar** [comment] 2020-01-20 01:12
I believe it's due to latency - whether on Blizzards end or yours. Either way, I can work around it in a future update.

**Comment by karyzan** [comment] 2020-01-20 01:21
> I believe it's due to latency - whether on Blizzards end or yours. Either way, I can work around it in a future update.

Alright brother. But I'm on a fiber line in Sweden so I don't know how it could be latency. It could be from blizzards end but I haven't felt any lag during raids. I got a DC cus I accidentally unplugged my ethernet cable that doesn't have the secure lock anymore

**Comment by karyzan** [comment] 2020-01-20 13:48
> I believe it's due to latency - whether on Blizzards end or yours. Either way, I can work around it in a future update.


webbeToday at 2:47 PM
Can you say to evil that I was not disconnected via my run and that I'm using a 1000/1000 connecting with like 40ms
My items were still not detected for that run.

**Comment by evil-morfar** [comment] 2020-01-20 13:56
A latency spike doesn't necessarily cause a disconnect. I can't say for sure that latency is the problem, but the matter of fact is there's an over 10 times longer delay than usual, which the addon does not handle properly.

**Comment by webbelito** [comment] 2020-01-20 19:39
@evil-morfar 

I noticed that I have recorded from one of the streams where it doesn't work, unfortunately, you can't see the chat... however I tried to distribute the loot with `/rc award`

Here's the link: https://www.twitch.tv/videos/534998326

Edit: Hopefully you can see if I was doing something unsupported or similar!

**Comment by evil-morfar** [comment] 2020-01-20 20:36
@webbelito Seems fine. 
Do note you can still use the addon by adding items manually with `/rc add [item1][item2]etc`. 
You can also do `/rc award` with the Session Frame containing the Ragnaros loot open to start a single session with all items (provided it hasn't bugged out :)).

**Comment by karyzan** [comment] 2020-01-20 21:08
> @webbelito Seems fine.
> Do note you can still use the addon by adding items manually with `/rc add [item1][item2]etc`.
> You can also do `/rc award` with the Session Frame containing the Ragnaros loot open to start a single session with all items (provided it hasn't bugged out :)).

Ohh. Very nice. Will try it next time. Yeah I did not do the /rc award with ragnaros loot open, only did it when I looted everything from him, since I thought the auto trade function would take place.

**Comment by evil-morfar** [comment] 2020-01-21 21:17
It should be fixed with v0.6.1 that I'm currently releasing. Please report back if you still have issues with this version, and otherwise thanks for your report.

**Closed as completed by evil-morfar** 2020-01-21 21:17 UTC

**Comment by karyzan** [comment] 2020-01-22 01:15
> It should be fixed with v0.6.1 that I'm currently releasing. Please report back if you still have issues with this version, and otherwise thanks for your report.

Thank you very much! It will be tried on Sunday unfortunately but we will have a reply as soon as we are done!
